spring:
  application:
    name: api-report

  datasource:
    url: jdbc:mysql://localhost:3306/petstore_system?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin@123

  jpa:
    hibernate:
      ddl-auto: none # report service only reads; schema is owned by api-order
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/petstore

server:
  port: 8083
